//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_BITMAP2                     156
#define IDB_Character_Stand_01          163
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_01 163
#define IDB_InGame_01                   165
#define IDC_CURSOR                      170
#define IDB_0                           221
#define IDB_1                           223
#define IDB_2                           224
#define IDB_3                           225
#define IDB_4                           226
#define IDB_5                           227
#define IDB_6                           228
#define IDB_7                           229
#define IDB_8                           230
#define IDB_9                           231
#define IDB_BITMAP14                    232
#define IDB_MINUS                       232
#define IDB_BITMAP23                    241
#define IDB_LOADING                     241
#define IDB_BITMAP26                    244
#define IDB_TOOLBAR                     244
#define IDB_CONTINUE                    245
#define MENU_INIT_02                    248
#define MENU_INIT_04                    250
#define MENU_INIT_06                    252
#define MENU_INIT_08                    254
#define MENU_INIT_10                    256
#define MENU_INIT_12                    258
#define MENU_INIT_14                    260
#define MENU_INIT_16                    262
#define MENU_INIT_18                    264
#define MENU_INIT_20                    266
#define MENU_INIT_22                    268
#define MENU_INIT_24                    270
#define MENU_INIT_26                    272
#define MENU_INIT_28                    274
#define MENU_INIT_30                    276
#define MENU_INIT_32                    278
#define MENU_INIT_34                    280
#define MENU_INIT_36                    282
#define MENU_INIT_38                    284
#define MENU_INIT_40                    286
#define MENU_INIT_42                    288
#define MENU_INIT_44                    290
#define MENU_INIT_46                    292
#define MENU_INIT_48                    294
#define MENU_ENTERMENU_01               295
#define MENU_ENTERMENU_02               296
#define MENU_ENTERMENU_03               297
#define MENU_ENTERMENU_04               298
#define MENU_ENTERMENU_05               299
#define MENU_ENTERMENU_06               300
#define MENU_ENTERMENU_07               301
#define MENU_ENTERMENU_08               302
#define MENU_ENTERMENU_09               303
#define MENU_ENTERMENU_10               304
#define MENU_ENTERMENU_11               305
#define MENU_ENTERMENU_12               307
#define MENU_ENTERMENU_OPTIONS          312
#define MENU_ENTERMENU_QUIT             313
#define MENU_ENTERMENU_SINGLE_PLAYER    314
#define LOADING                         315
#define LOADING_LEVEL                   316
#define JOIN                            318
#define MENU_OPTIONS                    320
#define MAP_HOME                        322
#define CHARACTER_DOWN_01               323
#define CHARACTER_DOWN_02               324
#define CHARACTER_DOWN_03               325
#define CHARACTER_DOWN_04               326
#define CHARACTER_DOWN_05               327
#define CHARACTER_DOWN_06               328
#define CHARACTER_DOWN_07               329
#define CHARACTER_DOWN_08               330
#define CHARACTER_DOWN_09               331
#define CHARACTER_DOWN_10               332
#define CHARACTER_UP_01                 333
#define CHARACTER_UP_02                 334
#define CHARACTER_UP_03                 335
#define CHARACTER_UP_04                 336
#define CHARACTER_UP_05                 337
#define CHARACTER_UP_06                 338
#define CHARACTER_UP_07                 339
#define CHARACTER_UP_08                 340
#define CHARACTER_UP_09                 341
#define CHARACTER_UP_10                 342
#define CHARACTER_STAND_DOWN            343
#define CHARACTER_STAND_LEFT            344
#define CHARACTER_STAND_RIGHT           345
#define CHARACTER_STAND_UP              346
#define CHARACTER_LEFT_01               347
#define CHARACTER_LEFT_02               348
#define CHARACTER_LEFT_03               349
#define CHARACTER_LEFT_04               350
#define CHARACTER_LEFT_05               351
#define CHARACTER_LEFT_06               352
#define CHARACTER_LEFT_07               353
#define CHARACTER_LEFT_08               354
#define CHARACTER_LEFT_09               355
#define CHARACTER_RIGHT_01              356
#define CHARACTER_RIGHT_02              357
#define CHARACTER_RIGHT_03              358
#define CHARACTER_RIGHT_04              359
#define CHARACTER_RIGHT_05              360
#define CHARACTER_RIGHT_06              361
#define CHARACTER_RIGHT_07              362
#define CHARACTER_RIGHT_08              363
#define CHARACTER_RIGHT_09              364
#define LIGHT_BEAM01                    374
#define LIGHT_BEAM02                    375
#define LIGHT_BEAM03                    379
#define LIGHT_BEAM04                    380
#define LIGHT_BEAM05                    381
#define IDB_BITMAP3                     382
#define MAP_HOME_WALL                   382
#define CHARACTER_RUN_LEFT_01           383
#define CHARACTER_RUN_LEFT_02           384
#define CHARACTER_RUN_LEFT_03           385
#define CHARACTER_RUN_DOWN_02           388
#define CHARACTER_RUN_DOWN_03           389
#define CHARACTER_RUN_DOWN_04           390
#define CHARACTER_RUN_RIGHT_01          394
#define CHARACTER_RUN_RIGHT_02          395
#define CHARACTER_RUN_RIGHT_03          396
#define CHARACTER_RUN_UP_01             397
#define CHARACTER_RUN_UP_02             398
#define CHARACTER_RUN_UP_03             399
#define CHARACTER_RUN_UP_04             400
#define CHARACTER_RUN_UP_05             401
#define CHARACTER_RUN_DOWN_01           402
#define CHARACTER_DASH_DOWN_01          403
#define CHARACTER_DASH_DOWN_02          404
#define IDB_BITMAP6                     405
#define CHARACTER_DASH_DOWN_03          405
#define IDB_BITMAP7                     406
#define CHARACTER_DASH_DOWN_04          406
#define CHARACTER_DASH_UP_01            407
#define CHARACTER_DASH_UP_02            408
#define CHARACTER_DASH_UP_03            409
#define CHARACTER_DASH_UP_04            410
#define CHARACTER_DASH_LEFT_01          411
#define CHARACTER_DASH_LEFT_02          412
#define CHARACTER_DASH_LEFT_03          413
#define CHARACTER_DASH_LEFT_04          414
#define CHARACTER_DASH_LEFT_05          415
#define CHARACTER_DASH_RIGHT_01         416
#define CHARACTER_DASH_RIGHT_02         417
#define CHARACTER_DASH_RIGHT_03         418
#define CHARACTER_DASH_RIGHT_04         419
#define IDB_BITMAP10                    420
#define CHARACTER_DASH_RIGHT_05         420
#define PRESS_F_01                      421
#define PRESS_F_02                      422
#define PRESS_F_03                      423
#define PRESS_F_04                      424
#define PRESS_F_05                      425
#define PRESS_F_06                      426
#define BOX_BOARD                       428
#define BOX_OFFENSE_01                  429
#define BOX_OFFENSE_02                  430
#define BOX_OFFENSE_03                  431
#define BOX_OFFENSE_04                  432
#define BOX_OFFENSE_05                  433
#define BOX_DEFENSE_01                  434
#define BOX_DEFENSE_02                  435
#define BOX_DEFENSE_03                  436
#define BOX_DEFENSE_04                  437
#define BOX_DEFENSE_05                  438
#define BOX_MISC_01                     439
#define BOX_MISC_02                     440
#define BOX_MISC_03                     441
#define BOX_MISC_04                     442
#define BOX_MISC_05                     443
#define MAP_TOWN                        444
#define IDB_BITMAP4                     445
#define MAP_TOWN_WALL                   445
#define CHARACTER_ARRIVAL_01            446
#define CHARACTER_ARRIVAL_02            447
#define CHARACTER_ARRIVAL_03            448
#define CHARACTER_ARRIVAL_04            449
#define CHARACTER_ARRIVAL_05            450
#define CHARACTER_ARRIVAL_06            451
#define CHARACTER_ARRIVAL_07            452
#define CHARACTER_ARRIVAL_08            453
#define CHARACTER_ARRIVAL_09            454
#define PAUSED_01                       455
#define PAUSED_02                       456
#define PAUSED_03                       457
#define PAUSED_04                       458
#define MENU_OPTIONSS                   459
#define UI_DIAMOND                      460
#define UI_HP_BAR                       461
#define UI_KEY_Q                        462
#define UI_KEY_SPACE                    463
#define UI_KEY_LEFT                     464
#define UI_MONEY                        465
#define UI_KEY_RIGHT                    466
#define UI_SKILL_BACKGROUND             467
#define UI_STATUS                       468
#define IDB_SLASH                       470
#define BOX_ITEM_BOARD                  471
#define BOX_CURSOR                      472
#define BOX_TEXT_DEFENSE                473
#define BOX_TEXT_MISC                   474
#define BOX_OFFENSE_TEXT                475
#define BOX_TEXT_OFFENSE                475
#define ITEM_UNKNOWN                    476
#define BAG_BOARD                       477
#define ITEM_OFFENSE_01                 478
#define ITEM_OFFENSE_02                 479
#define ITEM_MISC_01                    480
#define ITEM_MISC_02                    481
#define ITEM_DEFENSE_01                 482
#define ITEM_DEFENSE_02                 483
#define ITEM_DEFENSE_03                 484
#define IDB_BITMAP5                     486
#define ENEMY_BLOCKHEAD                 486
#define BOOK_BOARD                      487
#define BOOK_CURSOR                     488
#define SKILL_ICON_AIR_BURST            490
#define ITEM_SOLD_OUT                   491
#define BOX_EQUIP_BOARD                 492
#define SKILL_REBOUNDING_ICICLES_01     496
#define SKILL_REBOUNDING_ICICLES_02     497
#define SKILL_REBOUNDING_ICICLES_03     498
#define SKILL_REBOUNDING_ICICLES_04     499
#define IDB_BITMAP8                     500
#define SKILL_ICON_REBOUNDING_ICICLES   500
#define SKILL_ICON_AIR_SPINNER          501
#define SKILL_ICON_SHOCK_NOVA           502
#define BAG_ITEM_CURSOR                 503
#define SKILL_SHOCK_NOVA_01             504
#define SKILL_SHOCK_NOVA_02             505
#define SKILL_SHOCK_NOVA_03             506
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_01 514
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_02 515
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_03 516
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_04 517
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_05 518
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_06 519
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_07 520
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_08 521
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_09 522
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_10 523
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_11 524
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_12 525
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_13 526
#define CHARACTER_SKILL_SHOCK_NOVA_DOWN_14 527
#define BOOK_SKILL_DES_02               529
#define BOOK_SKILL_DES_01               530
#define BOOK_SKILL_DES_03               531
#define BOOK_SKILL_DES_04               532
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_01 533
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_02 534
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_03 535
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_04 536
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_05 537
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_06 538
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_07 539
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_08 540
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_09 541
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_10 542
#define CHARACTER_SKILL_REBOUNDING_ICICLES_DOWN_11 543
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_01 544
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_02 545
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_03 546
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_04 547
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_05 548
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_06 549
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_07 550
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_08 551
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_09 552
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_10 553
#define CHARACTER_SKILL_REBOUNDING_ICICLES_UP_11 554
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_01 555
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_02 556
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_03 557
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_04 558
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_05 559
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_06 560
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_07 561
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_08 562
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_09 563
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_10 564
#define CHARACTER_SKILL_REBOUNDING_ICICLES_LEFT_11 565
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_02 567
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_03 568
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_04 569
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_05 570
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_06 571
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_07 572
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_08 573
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_09 574
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_10 575
#define IDB_BITMAP21                    576
#define CHARACTER_SKILL_REBOUNDING_ICICLES_RIGHT_11 576
#define CHARACTER_SKILL_SHOCK_NOVA_UP_01 577
#define CHARACTER_SKILL_SHOCK_NOVA_UP_02 578
#define CHARACTER_SKILL_SHOCK_NOVA_UP_03 579
#define CHARACTER_SKILL_SHOCK_NOVA_UP_04 580
#define CHARACTER_SKILL_SHOCK_NOVA_UP_05 581
#define CHARACTER_SKILL_SHOCK_NOVA_UP_06 582
#define CHARACTER_SKILL_SHOCK_NOVA_UP_07 583
#define CHARACTER_SKILL_SHOCK_NOVA_UP_08 584
#define CHARACTER_SKILL_SHOCK_NOVA_UP_09 585
#define CHARACTER_SKILL_SHOCK_NOVA_UP_10 586
#define CHARACTER_SKILL_SHOCK_NOVA_UP_11 587
#define CHARACTER_SKILL_SHOCK_NOVA_UP_12 588
#define CHARACTER_SKILL_SHOCK_NOVA_UP_14 589
#define CHARACTER_SKILL_SHOCK_NOVA_UP_13 590
#define ENEMY_BLACK_MAN_STAND_LEFT      591
#define ENEMY_BLACK_MAN_STAND_RIGHT     592
#define ENEMY_BLACK_MAN_MOVE_LEFT_01    593
#define ENEMY_BLACK_MAN_MOVE_LEFT_02    594
#define ENEMY_BLACK_MAN_MOVE_LEFT_03    595
#define ENEMY_BLACK_MAN_MOVE_LEFT_04    596
#define ENEMY_BLACK_MAN_MOVE_RIGHT_01   597
#define ENEMY_BLACK_MAN_MOVE_RIGHT_02   598
#define ENEMY_BLACK_MAN_MOVE_RIGHT_03   599
#define ENEMY_BLACK_MAN_MOVE_RIGHT_04   600
#define GET_HURT_01                     601
#define GET_HURT_02                     602
#define GET_HURT_03                     603
#define GET_HURT_04                     604
#define GET_HURT_05                     605
#define GET_HURT_06                     606
#define GET_HURT_07                     607
#define ENEMY_BLACK_MAN_ATTACK_LEFT_01  608
#define ENEMY_BLACK_MAN_ATTACK_LEFT_02  609
#define ENEMY_BLACK_MAN_ATTACK_LEFT_03  610
#define ENEMY_BLACK_MAN_ATTACK_LEFT_04  611
#define ENEMY_BLACK_MAN_ATTACK_LEFT_05  612
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_01 613
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_02 614
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_03 615
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_04 616
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_05 617
#define ENEMY_BLACK_MAN_ATTACK_LEFT_06  618
#define ENEMY_BLACK_MAN_ATTACK_LEFT_07  619
#define ENEMY_BLACK_MAN_ATTACK_LEFT_08  620
#define ENEMY_BLACK_MAN_ATTACK_LEFT_09  621
#define ENEMY_BLACK_MAN_ATTACK_LEFT_10  622
#define ENEMY_BLACK_MAN_ATTACK_LEFT_11  623
#define ENEMY_BLACK_MAN_ATTACK_LEFT_12  624
#define ENEMY_BLACK_MAN_ATTACK_LEFT_13  625
#define ENEMY_BLACK_MAN_ATTACK_LEFT_14  626
#define ENEMY_BLACK_MAN_ATTACK_LEFT_15  628
#define ENEMY_BLACK_MAN_ATTACK_LEFT_16  629
#define ENEMY_BLACK_MAN_ATTACK_LEFT_17  630
#define ENEMY_BLACK_MAN_ATTACK_LEFT_18  631
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_06 632
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_07 633
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_08 634
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_09 635
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_10 636
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_11 637
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_12 638
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_13 639
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_14 640
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_15 641
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_16 642
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_17 643
#define ENEMY_BLACK_MAN_ATTACK_RIGHT_18 644
#define ENEMY_BLACK_MAN_HURT_LEFT       645
#define ENEMY_BLACK_MAN_HURT_RIGHT      646
#define CHARACTER_HURT_LEFT             647
#define CHARACTER_HURT_RIGHT            648
#define MAP_LEVEL_01                    650
#define LOADING_CHESS                   651
#define ENEMY_HP_BAR_SMALL              652
#define ENEMY_HP_BAR_M                  652
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        653
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
